2023-07-31 17:28:58,661 | main_logger | MainProcess  |        <module>               | INFO  | Master execution started
2023-07-31 17:28:58,662 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the create_folder_structure function
2023-07-31 17:28:58,665 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the common_files_downloads function
2023-07-31 17:29:03,019 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the orchestrate_calling function
2023-07-31 17:29:03,048 | main_logger | MainProcess  |        task_orc_execution     | INFO  | execution at task level
2023-07-31 17:29:06,331 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
2023-07-31 17:29:31,430 | main_logger | MainProcess  |        task_orc_execution     | ERROR | error in orchestrate_task_calling .
Traceback (most recent call last):
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 608, in task_orc_execution
    execute_job(prj_nm,paths_data,task_nm,run_id,file_path,iter_value)
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 38, in execute_job
    raise error
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 35, in execute_job
    download.execute_engine(prj_nm,task_id,paths_data,run_id,file_path,iter_value)
  File "/home/nandishms/test/download.py", line 267, in execute_engine
    raise error
  File "/home/nandishms/test/download.py", line 263, in execute_engine
    engine_code.engine_main(prj_nm,task_name,config_path,run_id,file_path,iter_value)
  File "/home/nandishms/test//src/scripts/engine_main/engine_code.py", line 476, in engine_main
    raise error
  File "/home/nandishms/test//src/scripts/engine_main/engine_code.py", line 370, in engine_main
    for i in data_fram :
  File "/home/nandishms/test//src/scripts/ingestion/rest_api_read.py", line 120, in read
    raise error
  File "/home/nandishms/test//src/scripts/ingestion/rest_api_read.py", line 71, in read
    to_get_api_details(json_data, "source",config_file_pathh)
  File "/home/nandishms/test//src/scripts/ingestion/rest_api_read.py", line 57, in to_get_api_details
    raise error
  File "/home/nandishms/test//src/scripts/ingestion/rest_api_read.py", line 43, in to_get_api_details
    access_token = decrypt(connection_details["access_token"])
  File "/home/nandishms/test//src/scripts/ingestion/utility.py", line 85, in decrypt
    decrypted = aesgcm.decrypt(IV, bytes.fromhex(data), None)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 202, in decrypt
    return aead._decrypt(backend, self, nonce, data, associated_data, 16)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/aead.py", line 163, in _decrypt
    raise InvalidTag
cryptography.exceptions.InvalidTag
2023-07-31 17:29:31,448 | main_logger | MainProcess  |        get_ind_task_status    | INFO  | rest_api_test task is FAILED
2023-07-31 17:29:31,449 | main_logger | MainProcess  |        task_orc_execution     | INFO  | Task rest_api_test Execution failed.
2023-07-31 17:29:35,156 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
