2023-08-01 13:33:58,655 | task_logger | MainProcess  |        execute_engine         | INFO  | entered into execute_engine
2023-08-01 13:33:58,655 | task_logger | MainProcess  |        execute_engine         | INFO  | calling the task_json_download function
2023-08-01 13:33:59,652 | task_logger | MainProcess  |        download_task_files    | INFO  | entered into downloading task related files
2023-08-01 13:34:00,588 | task_logger | MainProcess  |        download_task_files    | ERROR | error in download_task_files 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}.
Traceback (most recent call last):
  File "/home/nandishms/test/download.py", line 150, in download_task_files
    download_file_from_github(repo_name, branch,
  File "/home/nandishms/test/master.py", line 121, in downlaod_file_from_git
    file_contents = repo.get_contents(file_path,ref=branch).decoded_content
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Repository.py", line 2107, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}
2023-08-01 13:34:00,591 | task_logger | MainProcess  |        execute_engine         | ERROR | error in executing engine 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}.
Traceback (most recent call last):
  File "/home/nandishms/test/download.py", line 220, in execute_engine
    download_task_files(prj_nm,task_name, config_path, repo_name,GIT_BRANCH)
  File "/home/nandishms/test/download.py", line 182, in download_task_files
    raise error
  File "/home/nandishms/test/download.py", line 150, in download_task_files
    download_file_from_github(repo_name, branch,
  File "/home/nandishms/test/master.py", line 121, in downlaod_file_from_git
    file_contents = repo.get_contents(file_path,ref=branch).decoded_content
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Repository.py", line 2107, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}
