2023-07-31 16:39:06,296 | main_logger | MainProcess  |        <module>               | INFO  | Master execution started
2023-07-31 16:39:06,296 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the create_folder_structure function
2023-07-31 16:39:06,296 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the common_files_downloads function
2023-07-31 16:39:07,587 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the orchestrate_calling function
2023-07-31 16:39:07,589 | main_logger | MainProcess  |        task_orc_execution     | INFO  | execution at task level
2023-07-31 16:39:10,557 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
2023-07-31 16:39:12,556 | main_logger | MainProcess  |        task_orc_execution     | ERROR | error in orchestrate_task_calling 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}.
Traceback (most recent call last):
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 608, in task_orc_execution
    execute_job(prj_nm,paths_data,task_nm,run_id,file_path,iter_value)
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 38, in execute_job
    raise error
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 35, in execute_job
    download.execute_engine(prj_nm,task_id,paths_data,run_id,file_path,iter_value)
  File "/home/nandishms/test/download.py", line 242, in execute_engine
    raise error
  File "/home/nandishms/test/download.py", line 232, in execute_engine
    download_task_files(prj_nm,task_name, config_path, repo_name,GIT_BRANCH)
  File "/home/nandishms/test/download.py", line 197, in download_task_files
    raise error
  File "/home/nandishms/test/download.py", line 169, in download_task_files
    download_file_from_github(repo_name, branch,
  File "/home/nandishms/test/master.py", line 121, in downlaod_file_from_git
    file_contents = repo.get_contents(file_path,ref=branch).decoded_content
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Repository.py", line 2107, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/home/nandishms/.local/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}
2023-07-31 16:39:12,560 | main_logger | MainProcess  |        get_ind_task_status    | INFO  | Tetst1 task is Start
2023-07-31 16:39:12,560 | main_logger | MainProcess  |        task_orc_execution     | INFO  | Task Tetst1 Execution failed.
2023-07-31 16:39:15,878 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
